name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
#      - name: Test
#        run: npm test
      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: build
#          branch: gh-pages
#          token: ${{ secrets.GITHUB_TOKEN }}
